on: [push, pull_request]

name: build

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release', mariadb: true}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - if: ${{ !matrix.config.mariadb }}
        name: Install MySQL
        uses: ankane/setup-mysql@v1
        with:
          database: dbx_test
      - if: ${{ startsWith(matrix.config.os, 'windows') }}
        run: |
          mysql -u root -e "CREATE USER 'runneradmin'@'localhost' IDENTIFIED BY ''"
          mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'runneradmin'@'localhost'"
          mysql -u root -e "FLUSH PRIVILEGES"

      - if: ${{ matrix.config.mariadb }}
        name: Install MariaDB
        uses: ankane/setup-mariadb@v1
        with:
          database: dbx_test
      - if: ${{ matrix.config.mariadb }}
        run: |
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'runner'@'localhost' IDENTIFIED BY ''"
          mysql -e "FLUSH PRIVILEGES"

      - name: Install Postgres
        uses: ankane/setup-postgres@v1
        with:
          database: dbx_test

      - if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
        run: sudo apt-get install odbc-mariadb odbc-postgresql
      - if: ${{ startsWith(matrix.config.os, 'macos') }}
        run: brew install mariadb-connector-odbc psqlodbc

      - uses: r-lib/actions/check-r-package@v2
