on: workflow_dispatch

name: revdepcheck

jobs:
  revdepcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - run: Rscript -e 'pak::pkg_install("r-lib/revdepcheck")'
      - run: Rscript -e 'revdepcheck::revdep_check()'

      - run: cat revdep/cran.md
      - run: cat revdep/problems.md
      - run: cat revdep/failures.md
